### ISSUE TITLE
Add Ktlint / detekt

### ISSUE THREAD

**Issue by junwooYeom** [Compose-Picker/Picker#15]
### 🔍️ Description

- describe the feature

  

### 📌 Tasks 

- [ ] task1
- [ ] task2
- [ ] task3

**Comment by ows3090** [comment]
I think it would be better to just apply detekt.
ktlint, detekt have different purposes and I experiened to feel little discomfort when i applied ktlint.
ktlint is used to follow and set coding convention like trailing comma, max lines etc.
However, we may encounter ktlint error depending on whether we install ktlint plugin.
And then we already set coding convention written in wiki.

So I want to apply only detekt. How do you think? 
@junwooYeom @Lee-Jun-Young @lee989898 @Ddudduu

**Comment by junwooYeom** [comment]
Is there any disadvantage that only using detekt?? If not, only using detekt will be fine I think.

**Comment by ows3090** [comment]
it's enough to replace ktlint with detekt.
I think there are not any disadvantage.

**Comment by ghost** [comment]
I also think it would be better to just use detekt. I think using ktlint is unnecessary redundancy.

**Comment by Lee-Jun-Young** [comment]
I also believe that using detekt is a good idea since I have already established a code convention.

**Comment by Ddudduu** [comment]
I think using only detekt is a better option👍
