### ISSUE TITLE
Create Coding Convention Rule

### ISSUE THREAD

**Issue by junwooYeom** [Compose-Picker/Picker#4]
Write those convention on [here](https://github.com/Compose-Picker/Picker/wiki/Code-Convention)

**Comment by ghost** [comment]
![image](https://github.com/Compose-Picker/Picker/assets/90037701/0bb150b8-5659-485e-ac8e-5002d854121c)

I think the object and sealed class parts are the same in both do and don't.
Is it correct that the object and sealed class in the dont part are all uppercase?

**Comment by ows3090** [comment]
@lee989898 
yes. I think so too.
