### ISSUE TITLE
Create Git Convention

### ISSUE THREAD

**Issue by junwooYeom** [Compose-Picker/Picker#5]
Write those convention [here](https://github.com/Compose-Picker/Picker/wiki/Branch-Convention)

**Comment by Lee-Jun-Young** [comment]
@junwooYeom @ows3090 @Ddudduu @lee989898
I've posted a Git convention on the wiki. Please confirm.

**Comment by ows3090** [comment]
@Lee-Jun-Young @junwooYeom @Ddudduu @lee989898 
Should I use the commit message written on the wiki?

**Comment by Lee-Jun-Young** [comment]
I don't think it's confirmed yet, so I don't feel the need to follow it right away. What do you all think?

**Comment by ghost** [comment]
@Lee-Jun-Young 

I think so too
